version: "3.5"
services:
  app-back-builder:
    image: app-back-builder
    container_name: app-back-builder
    build:
      context: ./app-back
      dockerfile: Dockerfile
      target: builder
      args:
        - ENV=${ENV:-dev}
        - DD_VERSION=${VERSION_TAG:-0.0.1}
      x-bake:
        cache-from: type=registory,ref=${CACHE_GAR_PATH:-}/app-back-builder:build-cache
        cache-to: type=registory,ref=${CACHE_GAR_PATH:-}/app-back-builder:build-cache
  app-back:
    image: app-back
    container_name: app
    build:
      context: ./app-back
      dockerfile: Dockerfile
      target: builder
      args:
        - ENV=${ENV:-dev}
        - DD_VERSION=${VERSION_TAG:-0.0.1}
      x-bake:
        cache-from: type=registory,ref=${CACHE_GAR_PATH:-}/app-back:build-cache
        cache-to: type=registory,ref=${CACHE_GAR_PATH:-}/app-back:build-cache
  app-front-builder:
    image: app-front-builder
    container_name: app-front-builder
    build:
      context: ./app-front
      dockerfile: Dockerfile
      target: builder
      args:
        - ENV=${ENV:-dev}
        - DD_VERSION=${VERSION_TAG:-0.0.1}
      x-bake:
        cache-from: type=registory,ref=${CACHE_GAR_PATH:-}/app-front-builder:build-cache
        cache-to: type=registory,ref=${CACHE_GAR_PATH:-}/app-front-builder:build-cache
  app-front:
    image: app-front
    container_name: app
    build:
      context: ./app-front
      dockerfile: Dockerfile
      target: builder
      args:
        - ENV=${ENV:-dev}
        - DD_VERSION=${VERSION_TAG:-0.0.1}
      x-bake:
        cache-from: type=registory,ref=${CACHE_GAR_PATH:-}/app-front:build-cache
        cache-to: type=registory,ref=${CACHE_GAR_PATH:-}/app-front:build-cache
  